name: angular-libs pipeline build

on:
  push:
    branches:
      - "*"

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@berlingoqc"
      - name: Install
        run: npm ci
      - name: Build
        run: ./scripts/make.sh build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
