name: angular-libs pipeline release

on:
  release:
    types: [released]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@berlingoqc"
      - name: Install
        run: npm ci
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Build and update version
        run: ./scripts/make.sh build-release
      - name: Portal docker-build
        run: ./scripts/make.sh publish
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
